package telas;

import apoio.ManipularImagem;
import dao.ArquivoDao;
import dao.ContaPagarDao;
import dao.Dao;
import entidades.Arquivo;
import entidades.ContaPagar;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class JdlContasPagar extends javax.swing.JDialog {

    ContaPagar contaPagar = new ContaPagar();
    ArquivoDao arqDao = new ArquivoDao();
    ContaPagarDao contaPagarDao = new ContaPagarDao();
    Dao d = new Dao();
    String botaopressionado = "novo";
    File arquivo;
    private JTextField filename = new JTextField(), dir = new JTextField();
    BufferedImage imagem;

    public JdlContasPagar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        contaPagarDao.populaContaPagar(tblContasPagar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botoes = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        btnAnexar = new javax.swing.JButton();
        btnExibirAnexo = new javax.swing.JButton();
        btnRemoverAnexo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txfBuscar1 = new javax.swing.JTextField();
        Btnbuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContasPagar = new javax.swing.JTable();
        Btnpagamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contas Pagar");

        Botoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/adicionar.png"))); // NOI18N
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        btnAnexar.setText("Anexar Imagem");
        btnAnexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnexarActionPerformed(evt);
            }
        });

        btnExibirAnexo.setText("Exibir Anexo");
        btnExibirAnexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirAnexoActionPerformed(evt);
            }
        });

        btnRemoverAnexo.setText("Remover Anexo");
        btnRemoverAnexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverAnexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotoesLayout = new javax.swing.GroupLayout(Botoes);
        Botoes.setLayout(BotoesLayout);
        BotoesLayout.setHorizontalGroup(
            BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnexar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExibirAnexo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoverAnexo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BotoesLayout.setVerticalGroup(
            BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExibirAnexo)
                        .addComponent(btnAnexar)
                        .addComponent(btnRemoverAnexo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Buscar :");

        Btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Search.png"))); // NOI18N

        tblContasPagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblContasPagar);

        Btnpagamento.setText("Pagamento");
        Btnpagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btnpagamento)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Botoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txfBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Botoes, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btnpagamento)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(692, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tblContasPagar.getSelectedRow();
        if (linha > -1) {
            botaopressionado = "editar";
            int codCont = Integer.valueOf(String.valueOf(tblContasPagar.getValueAt(linha, 0)));
            ContaPagar contaPagar = contaPagarDao.procurarPorId(codCont);
            JdlCadastroContasPagar telaContasPagar = null;
            try {
                telaContasPagar = new JdlCadastroContasPagar(null, true,tblContasPagar);
                telaContasPagar.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(JdlContasPagar.class.getName()).log(Level.SEVERE, null, ex);
            }            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Produto!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        JdlCadastroContasPagar jdlCadastroContasPagar = new JdlCadastroContasPagar(null, false);
        jdlCadastroContasPagar.setVisible(true);
        contaPagarDao.populaContaPagar(tblContasPagar);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
        int linha = tblContasPagar.getSelectedRow();
        if (linha > -1) {
            int resposta = 0;
            int codContaPagar = Integer.valueOf(String.valueOf(tblContasPagar.getValueAt(tblContasPagar.getSelectedRow(), 0)));
            resposta = JOptionPane.showConfirmDialog(this, "Deseja Realmente Excluir?");
            if (resposta == JOptionPane.YES_OPTION) {
                contaPagar = contaPagarDao.procurarPorId(codContaPagar);
                d.excluir(contaPagar, contaPagar.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma Conta!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }
            contaPagarDao.populaContaPagar(tblContasPagar);
        }
    }//GEN-LAST:event_btexcluirActionPerformed

    private void BtnpagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpagamentoActionPerformed
       int linha = tblContasPagar.getSelectedRow();
        if (linha > -1) {
            botaopressionado = "editar";
            int codCont = Integer.valueOf(String.valueOf(tblContasPagar.getValueAt(linha, 0)));
            ContaPagar contaPagar = contaPagarDao.procurarPorId(codCont);
            JdlPagarConta jdlPagarConta = new JdlPagarConta(null, false);
            jdlPagarConta.setVisible(true);            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Produto!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_BtnpagamentoActionPerformed

    private void btnAnexarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnexarActionPerformed
        int linha = tblContasPagar.getSelectedRow();
        if (linha > -1) {
            int codContaPagar = Integer.valueOf(String.valueOf(tblContasPagar.getValueAt(linha, 0)));
            if (!arqDao.possuiAnexo(codContaPagar)) {               
            ContaPagar contaPagar = contaPagarDao.procurarPorId(codContaPagar);
            JFileChooser fc = new JFileChooser();
            int res = fc.showOpenDialog(null);
            if (res == JFileChooser.APPROVE_OPTION) {
                File arquivo = fc.getSelectedFile();
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 1000, 700);
                try {
                    Arquivo arq = new Arquivo();
                    arq.setArquivo(ManipularImagem.getImgBytes(imagem));
                    arq.setIdcontapagar(contaPagar);
                    d.salvar(arq);
                    JOptionPane.showMessageDialog(rootPane, "Anexo Enviado");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "Anexo não Enviado");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
            }
            } else{
                JOptionPane.showMessageDialog(null, "Essa Conta Já Possui Anexo!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Conta!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAnexarActionPerformed

    private void btnExibirAnexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirAnexoActionPerformed
        int linha = tblContasPagar.getSelectedRow();
        if (linha > -1) {
            int codContaPagar = Integer.valueOf(String.valueOf(tblContasPagar.getValueAt(linha, 0)));
            if (arqDao.possuiAnexo(codContaPagar)) {
                ContaPagar contaPagar = contaPagarDao.procurarPorId(codContaPagar);
                JdlExibirAnexo telaAnexo = new JdlExibirAnexo(null, rootPaneCheckingEnabled, contaPagar.getIdcontaPagar());
                telaAnexo.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Essa Conta Não Possui Anexo!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Conta!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnExibirAnexoActionPerformed

    private void btnRemoverAnexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverAnexoActionPerformed
        int linha = tblContasPagar.getSelectedRow();
        if (linha > -1) {
            int codContaPagar = Integer.valueOf(String.valueOf(tblContasPagar.getValueAt(linha, 0)));
            if (arqDao.possuiAnexo(codContaPagar)) {
                ContaPagar contaPagar = contaPagarDao.procurarPorId(codContaPagar);
                Arquivo arq = arqDao.buscarPorId(codContaPagar);
                d.excluir(arq, "Anexo Excluido!");
                JOptionPane.showMessageDialog(rootPane, "Anexo Excluído");
            } else {
                JOptionPane.showMessageDialog(null, "Essa Conta Não Possui Anexo!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Conta!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverAnexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdlContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdlContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdlContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdlContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdlContasPagar dialog = new JdlContasPagar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botoes;
    private javax.swing.JButton Btnbuscar;
    private javax.swing.JButton Btnpagamento;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btnAnexar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExibirAnexo;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemoverAnexo;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblContasPagar;
    private javax.swing.JTextField txfBuscar1;
    // End of variables declaration//GEN-END:variables
}
